In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import statistics

In [18]:
import sklearn.preprocessing

In [2]:
df = pd.read_csv("churn_modeling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,1,1.00,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0.00,1,112542.58,0.0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1.00,0,113931.57,1.0
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0.00,0,93826.63,0.0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1.00,1,79084.10,0.0

In [4]:
df.drop(columns=['RowNumber', 'Surname', 'CustomerId'], axis=1, inplace=True)

In [5]:
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,1,1.00,1,101348.88,1,NaN,NaN
1,608,Spain,Female,41,1,83807.86,1,0.00,1,112542.58,0.0
2,502,France,Female,42,8,159660.80,3,1.00,0,113931.57,1.0
3,699,France,Female,39,1,0.00,2,0.00,0,93826.63,0.0
4,850,Spain,Female,43,2,125510.82,1,1.00,1,79084.10,0.0

In [13]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [14]:
# Handling missing values
df.Gender.mode()

0    Male
Name: Gender, dtype: object

## Label Encoding

Helps us to transform categorical variables into numerical variables by assigning as number values of each of the categories.

In [ ]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

In [23]:
df['Gender_labels'] = le.fit_transform(df.Gender.values)
# fit → learn all the unique categories (e.g., "Male", "Female")
# transform → convert those categories into numbers

In [24]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_labels
0,619,France,Female,42,1,1.00,1,101348.88,1,NaN,NaN,0
1,608,Spain,Female,41,1,83807.86,1,0.00,1,112542.58,0.0,0
2,502,France,Female,42,8,159660.80,3,1.00,0,113931.57,1.0,0
3,699,France,Female,39,1,0.00,2,0.00,0,93826.63,0.0,0
4,850,Spain,Female,43,2,125510.82,1,1.00,1,79084.10,0.0,0

In [25]:
df.Gender_labels.value_counts()

Gender_labels
1    5457
0    4543
Name: count, dtype: int64

## One Hot Encoding

Its used when independent variables are nominal.

creates K diff columns each for a category.

replace one column with 1 and rest are 0s, 0 -> absence & 1 -> presence

In [26]:
# pd.get_dummies(), a Pandas function used for one-hot encoding categorical variables.
# it onverts categorical text/data into binary (0/1) columns.
one_hot = pd.get_dummies(df['Geography'])

In [27]:
one_hot.head()

   France  Germany  Spain
0    True    False  False
1   False    False   True
2    True    False  False
3    True    False  False
4   False    False   True

In [30]:
df_dummies = pd.get_dummies(df)
df_dummies.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_labels,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,1,1.00,1,101348.88,1,NaN,NaN,0,True,False,False,True,False
1,608,41,1,83807.86,1,0.00,1,112542.58,0.0,0,False,False,True,True,False
2,502,42,8,159660.80,3,1.00,0,113931.57,1.0,0,True,False,False,True,False
3,699,39,1,0.00,2,0.00,0,93826.63,0.0,0,True,False,False,True,False
4,850,43,2,125510.82,1,1.00,1,79084.10,0.0,0,False,False,True,True,False